steps:
# Step 1: Build the Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/lateral-booking-419709/mysql-crud-with-node-js-api', '.']

# Step 2: Push the image to the Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/lateral-booking-419709/mysql-crud-with-node-js-api']
