apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: gke-cicd-pipeline
  labels:
    app: nodejs
description: cicd delivery pipeline
serialPipeline:
  stages:
  - targetId: dev